name: GitHub Actions APP GIFS
on:
  push:
    branches:
      - main

jobs:
  Actions-GitHub-APPGIFS:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: npm ci
      - name: Bundle
        run: npm buld
